# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 333)
        self.hello_world_label = QtWidgets.QLabel(Form)
        self.hello_world_label.setGeometry(QtCore.QRect(150, 50, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(True)
        self.hello_world_label.setFont(font)
        self.hello_world_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hello_world_label.setObjectName("hello_world_label")
        self.click_me_button = QtWidgets.QPushButton(Form, clicked= lambda: self.press_it())
        self.click_me_button.setGeometry(QtCore.QRect(180, 240, 181, 41))
        self.click_me_button.setObjectName("click_me_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def press_it(self):
        self.hello_world_label.setText("Zort")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.hello_world_label.setText(_translate("Form", "Hello World"))
        self.click_me_button.setText(_translate("Form", "Click Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
